### PR TITLE
Refactor lua initialization

### PR DESCRIPTION
**Pull request by jyscao**
- simplify conditionals for lua and luac exe
- redent a conditional block

### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

Simplified 2 conditionals to improve maintainability.

### CODE REVIEW

**Comment by jyscao** [comment]
Also fixed the lua repl conditional, which should have indexed the first element in the list of luaexe

**Comment by wsdjeg** [comment]
thanks. if this pr has been done. I will merge it.

**Comment by jyscao** [comment]
This PR is done. Thanks

*Jethro Cao*

**Comment by wsdjeg** [comment]
merged thanks

**Pull request merged**
