### PR TITLE
Add layer for Pony programming language

### PR DESCRIPTION
**Pull request by oldstager**

### CODE REVIEW

**Comment by wsdjeg** [comment]
how about https://github.com/jmcomets/vim-pony

any plan to include it?

**Comment by crisidev** [comment]
@wsdjeg, the plugin you posted is not for po ylang, but for Django and python.

**Comment by bpdp** [comment]
yes @crisidev is right. This PR is for https://www.ponylang.org

**Comment by wsdjeg** [comment]
Thanks, I just test this layer, as @oldstager include this plugin with `on_ft` option, so only when filetype is change to pony, the plugin will be loaded, but before this plugin is loaded, the ftdetect is not work. I think we should make the ftdetect script not lazy loed.

**Comment by wsdjeg** [comment]
@Shougo how does dein deal with `ftdetect` script, when we set `on_ft` option?

**Pull request merged**
