### PR TITLE
Add option to show hidden files in filetree

### LINKED ISSUE #3102: Add config option to show hidden files (dotfiles) by default
**Is your feature request related to a problem? Please describe.**
I would like a way to show hidden files in the tree without having to toggle every time.

**Describe the solution you'd like**
Add a configuration property in init.toml to control file visibility.

**Describe alternatives you've considered**
Use a bootstrap function.

**Additional context**
As a devops engineer, I frequently work on dotfiles and it's tedious to toggle the feature every time I open SpaceVim.

Thanks for a fantastic project, btw!

### PR DESCRIPTION
**Pull request by wsdjeg**
close #3102

### CODE REVIEW

**Comment by txbm** [comment]
@wsdjeg This option did not work for `vimfiler` until I removed this line https://github.com/SpaceVim/SpaceVim/pull/1074/files#diff-35ec4e6359c7d42d90b009395020032aR22

I think the ignore pattern takes precedence. In fact, I don't think [this option](https://github.com/SpaceVim/SpaceVim/pull/3103/files#diff-35ec4e6359c7d42d90b009395020032aR61) has any effect when that pattern is set.

**Comment by circld** [comment]
Agreed-- setting didn't do anything until I removed that line.

**Comment by materemias** [comment]
@petermelias could you create a pull request ?

**Comment by jajaperson** [comment]
Is there documentation for how to use this?

**Comment by aboettger-tuhh** [comment]
> Is there documentation for how to use this?

[SpaceVim core layer](https://spacevim.org/layers/core/)

**Pull request merged**
