### PR TITLE
Fix toggle comment line

### LINKED ISSUE #678: <Leader>cc brings up quickfix window rather than running NERDComment comment out command
## Expected behavior, english is recommended
\<Leader\>cc from Normal
Comment out the current line or text selected in visual mode.

## Environment Information
- OS: macOS 10.12.5
- neovim version: v0.2.0

## The reproduce ways from Vim starting (Required!)
\<Leader\>cc from Normal

Just \<Leader\>c will bring up the option c for Toggle comment lines help window, but no other options are shown.

c

## Output of the ':SPDebugInfo!'
?
please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
problem

### PR DESCRIPTION
**Pull request by wsdjeg**
close #678

### CODE REVIEW

**Comment by wsdjeg** [comment]
@jetm  I just add a new branch, in that branc `SPC c l` support visual mode, you can toggle lines.

**Comment by jetm** [comment]
@wsdjeg: I tested Visual_SPC branch, but it doesn't work when I tried to comment when I have selected a block in visual mode. Check out the video: https://asciinema.org/a/5WfLDOG2nleicMZvF7wdtL8Po

**Comment by wsdjeg** [comment]
Do you test  https://github.com/SpaceVim/SpaceVim/pull/696  ?

**Comment by jetm** [comment]
I have tested #696 I got the same negative result: from a selected lines, pressing `SPC c l` only one line is commented.

**Comment by wsdjeg** [comment]
Let's move to that PR.

**Pull request merged**
