### PR TITLE
Add Palenight ColorScheme

### PR DESCRIPTION
**Pull request by alanding1989**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?
add new colorscheme **palenight**.

**with** or **without** the below two commits all works. the two commits just add a bright statusline style. 
```
"update palenight colorscheme" && "fix palenight colorscheme"
```
**default statusline** color style is dark one if
```
g:spacevim_statusline_bright == 0  ||  exists(g:spacevim_statusline_bright) == 0
```
I have **not** added the global option   **g:spacevim_statusline_bright**  in  **autoload/SpaceVim.vim**

[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by wsdjeg** [comment]
thanks I will test it later。

**Comment by wsdjeg** [comment]
we have option `g:spacevim_colorscheme_bg` which is for setting background

**Comment by alanding1989** [comment]
> we have option `g:spacevim_colorscheme_bg` which is for setting background

this does not contain a complete light color scheme, it just contain light statusline color.
it just depends on you whether or not to use `g:spacevim_colorscheme_bg` to control the color loading logic. for me , it both ok.

**Comment by alanding1989** [comment]
> > we have option `g:spacevim_colorscheme_bg` which is for setting background
> 
> this does not contain a complete light color scheme, it just contain light statusline color.
> it just depends on you whether or not to use `g:spacevim_colorscheme_bg` to control the color loading logic. for me , it both ok.

without the below two commits it just define the dark statusline colorscheme.   the color palette is too complicated, I don`t know how to do to contain light statusline color style without changing logic in tabline.vim and statusline.vim files.

**commit**
```
"update palenight colorscheme" && "fix palenight colorscheme"
```

**Comment by wsdjeg** [comment]
Does this colorscheme provides dark and light theme?

**Comment by alanding1989** [comment]
> Does this colorscheme provides dark and light theme?

please check the link below

just dark scheme,   the first one commit contains a [dark style statusline](https://asciinema.org/a/8wT0MwBe8WBuoOppmBllmEZfx), 
the other two commits add a [more brighter statusline](https://asciinema.org/a/PXmy31MyY6DyVfxFt4ZlWyh5E) color style but the scheme is still dark.

**Comment by wsdjeg** [comment]
How about adding a layer option insead of global spacevim option?

**Comment by alanding1989** [comment]
> How about adding a layer option insead of global spacevim option?

this is a good idea, I have add this layer option, please check.

**Comment by wsdjeg** [comment]
~~if you do not set the layer option. then the theme function will cause error, as there is no such key.~~

**Pull request merged**
