### PR TITLE
Add screensaver layer

### PR DESCRIPTION
**Pull request by wsdjeg**
@tracyone  can you test it in item2? I found this plugin can not work well with true colors enabled.

### CODE REVIEW

**Comment by tracyone** [comment]
You are right.

 [t9md/vim-choosewin](https://github.com/t9md/vim-choosewin) is also not work.

I only use ScreenSaver password.

https://github.com/tracyone/t-vim/blob/master/rc/fun.vim

**Comment by wsdjeg** [comment]
@tracyone fork them or open issue for feature request?

**Comment by wsdjeg** [comment]
https://github.com/t9md/vim-choosewin/pull/30/files

I think vim-choosewin support true colors. I have test it, it works well for me.

**Comment by wsdjeg** [comment]
I am working on a fork.

https://github.com/itchyny/screensaver.vim/pull/4

**Comment by wsdjeg** [comment]
@tracyone true colors support has been done.

**Pull request merged**
