### PR TITLE
faq: using SpaceVim without overwrite vimrc

### LINKED ISSUE #1844: Feature request: don't overwrite .vimrc/init.vim
It would be really great if I could try SpaceVim without overwriting my .vimrc or init.vim. I'm not used to SpaceVim's workflow, and I can't afford to disrupt my current workflow. If SpaceVim created a file (e.g. `svim`) that invoked nvim or vim with a different configuration file, that would be much preferable to the current situation, and would allow me to learn to adapt to SpaceVim gradually.

Also, the installer *has* to warn you that your current configuration will be overwritten. It's not acceptable not to do that.

### PR DESCRIPTION
**Pull request by wsdjeg**
close #1844

### CODE REVIEW

**Comment by bluddy** [comment]
I think this is good, but perhaps this could also be the default behavior, both for vim and neovim? As a distribution, you don't want to overwrite the tools you're using -- they have their own 'distribution'.

**Comment by wsdjeg** [comment]
@bluddy, sorry, I can not make this behavior default, It is same behavior as spacemacs.

**Comment by bluddy** [comment]
But why do you need to be constrained by what spacemacs does?

**Comment by wsdjeg** [comment]
@bluddy ok, if we make this behavior default, It will break many things, when using gvim, you can not load SpaceVim, gvim do not using alias. 

This is just a vim config, it do not contains a exetable file, if we include vim into this repo, I would like to use new path instead of `~/.vim`.

**Pull request merged**
