### PR TITLE
Supporting eex in the elixir layer

### PR DESCRIPTION
**Pull request by jeregrine**
- [x] I have read and understood SpaceVim's [CONTRIBUTING][cont] document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT][code] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

The vim-elixir supports ftype elixir and eelixir which is used in `eex` templates. This is commonly used in HTML projects. I wasn't able to find any testing related to the elixir layer. 

[cont]: https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md
[code]: https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by jeregrine** [comment]
Why do I need to sign a CLA with SAP? At no point was this mentioned in the README, CONTRIBUTING.md or anywhere else in this project?

**Comment by wsdjeg** [comment]
@jeregrine sorry for missing this in the contributing.md, but we have use the `license/cla` checker for long time. and I will update the doc about this.

**Comment by jeregrine** [comment]
@wsdjeg but why?

**Comment by wsdjeg** [comment]
this is just like a agreement page, and it is why cla team create such project.  people who sign the cla, means they are agree with our SAP Individual Contributor License Agreement.

you can check the link in above comments from cla.

https://cla-assistant.io/SpaceVim/SpaceVim?pullRequest=1404

**Comment by jeregrine** [comment]
I read the Agreement and I don't want to sign it.

What does SAP have to do with any of this? This is a "community supported"
project. Not an SAP company.

If you want to take my code and improve the elixir integration by all
means.

But I won't be contributing anymore to this project outside of my own fork
if this CLA is required.

**Comment by wsdjeg** [comment]
@jeregrine I am really sorry, but I do not understand why community supported project can not use cla? I think spacevim team should accept the agreement.

**Comment by OvermindDL1** [comment]
I think it's the `SAP` part he has issues with, having worked in 'Big Business' myself I can see why he may have a bit of hatred for SAP itself.  ^.^;

**Comment by jeregrine** [comment]
Because the contract is with [SAP](https://www.sap.com/index.html). The license you are using for this project is MIT, already covers the project and contributors and has done so for decades. 

I can literally fork this project, claim it as my own, rename it, re-license it and sell it and no CLA can stop that. 

The point is, a CLA is a legal agreement and I don't feel like signing over my legal rights to SAP for a vim plugin.

**Comment by wsdjeg** [comment]
But I think all code pushed to spacevim should base on an agreement.  I don't want to have dispute with contributors in the future.

**Comment by wsdjeg** [comment]
@jeregrine Got it, thanks for your info.

**Comment by jeregrine** [comment]
If your employer (I presume SAP?) is requiring you to do a CLA, that is one thing and it sucks. 

If you are doing it because you saw other projects doing it and want to be like them, don't do it, its a huge waste of time and it solves nothing. Further your CLA is with SAP not "SpaceVim" which I presume is not a legal entity and thus can't hold a legal contract. 

The MIT licenses is permissive and gives you absolutely no control or recourse. If you want to avoid disputes you need to look into different software licenses.

**Comment by wsdjeg** [comment]
> The MIT licenses is permissive and gives you absolutely no control or recourse. If you want to avoid disputes you need to look into different software licenses.

any idea about new licenses?

**Comment by jeregrine** [comment]
I just wouldn't worry about it. Its SpaceVim, you're not gonna run into
issues. Drop the CLA and just be happy people are contributing.

**Comment by OvermindDL1** [comment]
I recommend the latest Apache licenses over MIT if you care about rights.  It is a litigation tested and battle hardened license that prevent patent trolling and so forth and all that.  As long as the contributors accept the apache license (which it's basically MIT except it has patent exemptions and no suing and other nice bits) then that covers most of what most CLA's cover already.

**Comment by OvermindDL1** [comment]
Also I see no issues with CLA's at all, in fact I find them very useful to make it so you don't have to confirm with every-past-contributor if you want to relicense to, say, apache from MIT.  But SAP is well known in many industries to be very...er...bad, so might just want to take them out of the wording I'd think...  ^.^;

**Comment by wsdjeg** [comment]
@jeregrine ok, just remove cla, feel free to reopen this PR.

**Comment by wsdjeg** [comment]
Thanks.

**Pull request merged**
