### PR TITLE
WIP: Update syntax checker layer

### LINKED ISSUE #200: recommend plugin:ale
https://github.com/w0rp/ale

Asynchronous Lint Engine,  it faster than any checker I have used, and the most importent is the feature of `lint while you type`

### LINKED ISSUE #547: SPC e c clear all errors does not work.
@blueyed

does neomake have function for clear all errors ( and close qf window)?

I have read the doc of neomake, I can not find the function for this feature.

### PR DESCRIPTION
**Pull request by wsdjeg**
Ref: https://github.com/SpaceVim/SpaceVim/issues/200

pick up #931

close #547 
close #200 
close #931 

# [Layers](https://spacevim.org/layers) > checkers

This layer provides syntax checking feature.

## Install

checkers layer is loaded by default.

## options

| Name                         | default value | description                                              |
| ---------------------------- | ------------- | -------------------------------------------------------- |
| `g:spacevim_enable_neomake`  | 1             | Use neomake as default checking tools                    |
| `g:spacevim_enable_ale`      | 0             | Use ale as default checking tools                        |
| `g:spacevim_lint_on_the_fly` | 0             | Syntax checking on the fly feature, disabled by default. |

**NOTE:** if you want to use  ale, you need:

```viml
let g:spacevim_enable_neomake = 0
let g:spacevim_enable_ale = 1
```

and if you want to use syntastic, set this two options to 0.

## Mappings

| Key       | mode   | description                                                  |
| --------- | ------ | ------------------------------------------------------------ |
| `SPC e c` | Normal | clear errors                                                 |
| `SPC e h` | Normal | describe current checker                                     |
| `SPC e n` | Normal | jump to the position of next error                           |
| `SPC e N` | Normal | jump to the position of previous error                       |
| `SPC e p` | Normal | jump to the position of previous error                       |
| `SPC e l` | Normal | display a list of all the errors                             |
| `SPC e L` | Normal | display a list of all the errors and focus the errors buffer |
| `SPC e e` | Normal | explain the error at point                                   |
| `SPC e s` | Normal | set syntax checker                                           |
| `SPC e S` | Normal | set syntax checker executable                                |
| `SPC e v` | Normal | verify syntax setup                                          |
| `SPC t s` | Normal | toggle syntax                                                |

### CODE REVIEW

**Comment by wsdjeg** [comment]
@blueyed It is not necessary to install neomake and ale and syntastic together, this will increase the number of plugins in a layer. I will add a new option `g:spacevim_enable_ale` for ale, just like `g:spacevim_enable_neomake`. but neomake will still be the default checker.

**Comment by wsdjeg** [comment]
@blueyed I get this error with neomake's java maker
```
let s:neomake_automake_events['TextChangedI'] = {'delay': 750}
```

````
Foo.java|1 error| class Foo is public, should be declared in a file named Foo.java
````

I think it is due to neomake's lint on the fly use tmp file, so the file name is not same as current file.

EDIT: this issue does not happened in ale, I think the ale use a tmp name same as current file name.

**Comment by crisidev** [comment]
@wsdjeg Another nice thing to have with ale is the number of warnings / errors in the status line.

This snippet applied to ```autoload/SpaceVim/layers/core/statusline.vim``` will do the trick:

```
if g:spacevim_enable_neomake
...
elseif g:spacevim_enable_ale
  function! s:syntax_checking()
    if !exists('g:ale_enabled')
      return ''
    endif
    let counts = ale#statusline#Count(bufnr(''))
    let warnings = counts.warning + counts.style_warning
    let errors = counts.error + counts.style_error
    let l =  warnings ? ' %#SpaceVim_statusline_warn#●' . warnings . ' ' : ''
    let l .=  errors ? (warnings ? '' : ' ') . '%#SpaceVim_statusline_error#●' . errors  . ' ' : ''
    return l
  endfunction
```

**Comment by crisidev** [comment]
I can open a PR for this specific function.

**Comment by wsdjeg** [comment]
@crisidev PR is welcome :smaile:

**Comment by blueyed** [comment]
> Another nice thing to have with ale is the number of warnings / errors in the status line.

Same for Neomake.  See `:h neomake-statusline`.

**Pull request merged**
