### PR TITLE
Add NeoSolarized guide theme

### PR DESCRIPTION
**Pull request by thawk**
# PR Prelude

Thank you for working on SpaceVim! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood SpaceVim's [CONTRIBUTING][cont] document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT][code] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Add NeoSolarized statusline theme

Migrate solarized statusline/tabline theme to NeoSolarized, compatibly with terminal and GUI, dark and light background.

[cont]: https://github.com/SpaceVim/SpaceVim/blob/dev/CONTRIBUTING.md
[code]: https://github.com/SpaceVim/SpaceVim/blob/dev/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by wsdjeg** [comment]
Hi, is it same as solarized? if it is you can use 

```vim
function! SpaceVim#mapping#guide#theme#NeoSolarized#palette() abort
  return SpaceVim#mapping#guide#theme#Solarized#palette()
endfunction
```

**Comment by thawk** [comment]
Yes,it's the same. I will update it.

**Comment by wsdjeg** [comment]
@thawk Thanks

**Comment by wsdjeg** [comment]
ohh, sorry, I merged it before you squash commits. :worried:

**Comment by thawk** [comment]
Should I create another PR to fix that?

**Comment by wsdjeg** [comment]
No, I it has been fixed, your commits has been merged. thanks for your PR.

**Pull request merged**
