### PR TITLE
Hotfix in windows 7

### PR DESCRIPTION
**Pull request by Gabirel**
# PR Prelude

- Use more flexible command to detect
- Let `Pause` command work

Thank you for working on SpaceVim! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood SpaceVim's [CONTRIBUTING][cont] document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT][code] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]

[cont]: https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md
[code]: https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by Gabirel** [comment]
@wsdjeg I've already tested it. It works for me. Please do one more test in your win7

**Comment by wsdjeg** [comment]
the default branch is master, and git pull origin dev will cause error.

**Comment by wsdjeg** [comment]
is there a function for checking if the path is a link to SpaceVim or directory?

**Comment by Gabirel** [comment]
1. What do you mean by this?
> the default branch is master, and git pull origin dev will cause error.

I didn't `git pull origin dev`. And There's no branch called `dev`.

2. Which path is linked to SpaceVim? I don't understand it. Maybe no.

**Comment by wsdjeg** [comment]
@Gabirel here is the link: https://github.com/Gabirel/SpaceVim/blob/a064dc0d278703e30244224b681c0e6ed0fd7798/docs/install.cmd#L77

**Review by wsdjeg — APPROVED** [review]

**Pull request merged**
