### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/SpaceVim ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by monkeywithacupcake** [comment]
You already had the contributor graph. This change to the readme adds the badges at the top for backers and sponsors and sections for them at the bottom.

**Comment by wsdjeg** [comment]
sorry， I do not add these info into readme，Only one link is enough. BTW, I do not understand how open Collective works.

**Comment by wsdjeg** [comment]
I have add link of Collective in http://spacevim.org/sponsors/

**Comment by monkeywithacupcake** [comment]
Understandable. If you want to know more - chat with other repo owners in the Open Collective slack channel. It is a very welcoming community.

**Comment by wsdjeg** [comment]
Thanks for your PR, I want to keep readme as simple as possible.

**Pull request closed without merging**
