### PR TITLE
Change: Leader guide g, z

### PR DESCRIPTION
**Pull request by alanding1989**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?
when I map these two key binding:
```
nmap  <silent> [g  <Plug>GitGutterPrevHunk
nmap  <silent> ]g  <Plug>GitGutterNextHunk
```
then I push [g to find previous hunk, there will be a delay, it is very annoying,  ]g does`t have this.
so change 
```
nmap g [g]   to ->  nmap g [G] ,    and   nmap z [z] to ->  nmap z [Z]
```
 

[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by wsdjeg** [comment]
you should checkout from spacevim master branch, why some many commits?

**Comment by alanding1989** [comment]
> you should checkout from spacevim master branch, why some many commits?

:cry:  I dont know why..  my forked SpaceVim repo will merge upstream SpaceVim/SpaceVim every few days, than will creat a commit 'merge spc', everytime I want to make a PR, I `git checkout -b` "some name" to creat a new branch and a PR. is this the normal process ?

**Comment by wsdjeg** [comment]
Ok, thanks, I will write some tips about how to send PR.

**Comment by alanding1989** [comment]
> Ok, thanks, I will write some tips about how to send PR.

I write a script to make things **ready** for creating a PR, I think right now doesnt need any manual operations...,   please check does it alright ?

```
#! /usr/bin/env bash

cd /tmp
rm ./SpaceVim | git clone git@github.com:SpaceVim/SpaceVim.git SpaceVim | cd ./SpaceVim
git checkout -b dev
git remote remove origin | git remote add origin git@github.com:alanding1989/SpaceVim.git
git remote add upstream git@github.com:SpaceVim:SpaceVIm.git
git push -u origin dev
```

**Comment by alanding1989** [comment]
> > Ok, thanks, I will write some tips about how to send PR.
> 
> I write a script to make things **ready** for creating a PR, I think right now doesnt need any manual operations..., please check does it alright ?
> 
> ```
> #! /usr/bin/env bash
> 
> cd /tmp
> rm -rf ./SpaceVim | git clone git@github.com:SpaceVim/SpaceVim.git SpaceVim | cd ./SpaceVim
> git checkout -b dev
> git remote remove origin | git remote add origin git@github.com:alanding1989/SpaceVim.git
> git remote add upstream git@github.com:SpaceVim:SpaceVIm.git
> git push -u origin dev
> ```

**Comment by alanding1989** [comment]
> > > Ok, thanks, I will write some tips about how to send PR.
> > 
> > 
> > I write a script to make things **ready** for creating a PR, I think right now doesnt need any manual operations..., please check does it alright ?
> > ```
> > #! /usr/bin/env bash
> > 
> > cd /tmp
> > rm -rf ./SpaceVim | git clone git@github.com:SpaceVim/SpaceVim.git SpaceVim && cd ./SpaceVim
> > git checkout -b dev
> > git remote remove origin && git remote add origin git@github.com:alanding1989/SpaceVim.git
> > git remote add upstream git@github.com:SpaceVim:SpaceVIm.git
> > git push -u origin dev
> > ```

**Comment by alanding1989** [comment]
> Ok, thanks, I will write some tips about how to send PR.


I write a script to make things **ready** for creating a PR, I think right now doesnt need any manual operations..., please check does it alright ?
```
#! /usr/bin/env bash

branchname=$1

cd /tmp
rm -rf ./SpaceVim | git clone git@github.com:SpaceVim/SpaceVim.git SpaceVim && cd ./SpaceVim
git checkout -b "$branchname"
git remote remove origin && git remote add origin git@github.com:alanding1989/SpaceVim.git
git remote add upstream git@github.com:SpaceVim:SpaceVIm.git
git push -u origin dev
```

**Comment by wsdjeg** [comment]
This should be done in local, I do not want to use script to do this, as people some time use differnet branch.

**Pull request merged**
