### PR TITLE
Fixed spelling, grammar, and formatting

### PR DESCRIPTION
**Pull request by camdencheek**
Edited docs to fix simple spelling and grammar mistakes. Also made formatting more consistent and readable. Tried to keep formatting as close to the original style as possible. Sorted colorschemes alphabetically.

### CODE REVIEW

**Comment by wsdjeg** [comment]
Oh, sorry, SpaceVim's doc is automatically generated by vim files, and we should edited vim files instead of txt.

But thanks for PR, I will merge this to vim files.

**Comment by camdencheek** [comment]
Oh! I'm sorry. I didn't intend to make more work for you. If you would like, I can go through and move those changes over to the vim files.

**Comment by wsdjeg** [comment]
Thanks, SpaceVim use google's vimdoc to generate txt file. You can check it out. If you have vimdoc in your PATH, SpaceVim will automatically generate txt when save a vim file.

**Comment by camdencheek** [comment]
Alright, I moved the documentation changes into the vimfiles, and it seemed to work fine with vimdoc. Let me know if there are any more issues.
Also, it's unfortunate that some of the formatting is so inflexible. It is difficult to get the numbered lists to look nice.

**Comment by wsdjeg** [comment]
Nice work.

And what do  `get the numbered lists to look nice` means?

**Comment by camdencheek** [comment]
In the original pull request, I had formatted the numbered lists like in the LANG#RUST section to a much cleaner, better aligned format. The way vimdoc converts the comments to indented text makes it impossible (to my knowledge) to get the lists to align that same way. It seems to have its own set of rules on when and where to indent the output docs, and I couldn't find any vimdoc documentation on how it formats lists and block quotes.

**Comment by wsdjeg** [comment]
I got it, it maybe the feature of vimdoc, let merge this PR first.

**Pull request merged**
