### PR TITLE
Add sidebar

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

merge tagbar and filetree into one sidebar:

### CODE REVIEW

**Comment by icearith** [comment]
Is this only work for markdown files?

**Comment by wsdjeg** [comment]
no, it should works well for all FileTypes.

**Comment by icearith** [comment]
wow @wsdjeg , where can I find the relevant docs for this feature? 

Is it provided by a layer or is it delivered by default?

**Comment by icearith** [comment]
wow @wsdjeg , where can I find the relevant docs for this feature? 

Is it provided by a layer or is it delivered by default?

**Comment by wsdjeg** [comment]
This feature has not been merged, maybe, this feature will be included into ui layer

**Pull request merged**
