### PR TITLE
Fixed: Right align '='.

### PR DESCRIPTION
**Pull request by xylinkun**
Fixed: Right align '='.

### CODE REVIEW

**Comment by wsdjeg** [comment]
what is the difference?


---

Shidong Wang

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] Fixed: Right align '='. (#2376)
发件人：ssfjhh
收件人：SpaceVim/SpaceVim
抄送：Subscribed


Fixed: Right align '='.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/SpaceVim/SpaceVim/pull/2376

Commit Summary

  *   Fixed: Right align '='.

File Changes

  *   M autoload/SpaceVim/layers/edit.vim<https://github.com/SpaceVim/SpaceVim/pull/2376/files#diff-0> (2)

Patch Links:

  *   https://github.com/SpaceVim/SpaceVim/pull/2376.patch
  *   https://github.com/SpaceVim/SpaceVim/pull/2376.diff

―

**Comment by xylinkun** [comment]
https://github.com/SpaceVim/SpaceVim/issues/2212#issuecomment-449192739

**Comment by wsdjeg** [comment]
ok, rebase and merged.

**Comment by wsdjeg** [comment]
Thanks, I have merged it.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Fixed: Right align '='. (#2376)
发件人：ssfjhh
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Review requested


#2212 (comment)<https://github.com/SpaceVim/SpaceVim/issues/2212#issuecomment-449192739>

―

**Pull request merged**
