### PR TITLE
Fix #2012

### LINKED ISSUE #2012: Setting 'verbose' flag to positive value breaks mappings guides.
## Expected behavior

It should display a window with a mapping guide and don't print any error messages.

## The reproduce ways from Vim starting

- `:set verbose=1`
- Type <kbd>s</kbd>, <kbd>\\</kbd>, or <kbd>SPC</kbd> and wait few seconds

## Actual behavior

It prints
```
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[20]..<SNR>34_start_parser:
line   14:
E716: Key not present in Dictionary: lhs =~ '<Plug>.*' || mapd.lhs =~ '<SNR>.*'
E15: Invalid expression: mapd.lhs =~ '<Plug>.*' || mapd.lhs =~ '<SNR>.*'
line   17:
E716: Key not present in Dictionary: rhs)
E116: Invalid arguments for function s:format_displaystring
E15: Invalid expression: s:format_displaystring(mapd.rhs)
line   18:
E716: Key not present in Dictionary: lhs, key, '', '')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(mapd.lhs, key, '', '')
line   19:
E716: Key not present in Dictionary: lhs, '<Space>', ' ', 'g')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(mapd.lhs, '<Space>', ' ', 'g')
line   20:
E716: Key not present in Dictionary: lhs, '<Tab>', '<C-I>', 'g')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(mapd.lhs, '<Tab>', '<C-I>', 'g')
line   21:
E716: Key not present in Dictionary: rhs, '<SID>', '<SNR>'.mapd['sid'].'_', 'g')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(mapd.rhs, '<SID>', '<SNR>'.mapd['sid'].'_', 'g')
line   22:
E716: Key not present in Dictionary: lhs != '' && mapd.display !~# 'LeaderGuide.*'
E15: Invalid expression: mapd.lhs != '' && mapd.display !~# 'LeaderGuide.*'
line   14:
E716: Key not present in Dictionary: lhs =~ '<Plug>.*' || mapd.lhs =~ '<SNR>.*'
E15: Invalid expression: mapd.lhs =~ '<Plug>.*' || mapd.lhs =~ '<SNR>.*'
line   17:
E716: Key not present in Dictionary: rhs)
E116: Invalid arguments for function s:format_displaystring
E15: Invalid expression: s:format_displaystring(mapd.rhs)
line   18:
E716: Key not present in Dictionary: lhs, key, '', '')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(mapd.lhs, key, '', '')
line   19:
E716: Key not present in Dictionary: lhs, '<Space>', ' ', 'g')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(mapd.lhs, '<Space>', ' ', 'g')
line   20:                                                                                                                                                             
E716: Key not present in Dictionary: lhs, '<Tab>', '<C-I>', 'g')                                                                                                       
E116: Invalid arguments for function substitute
```

The mapping guide is displayed after that normally.

# Debug info

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.1
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_autocomplete_parens = 1
g:spacevim_automatic_update = 1
g:spacevim_buffer_index_type = 1
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = [['junegunn/vim-easy-align'], ['blindFS/vim-taskwarrior'], ['simnalamburt/vim-mundo'], ['WolfgangMehner/c-support'], ['vim-latex/vim-latex']]
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_disabled_plugins = ['java_getset.vim']
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 1
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_statusline_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_enable_vimfiler_filetypeicon = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_plugin_bundle_dir = '/home/arch/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_processes = 16
g:spacevim_plugin_name = 'helpful.vim'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'package.json']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 45
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'fire'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_version = '0.9.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:16:34] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [00:16:35] [ Info ] Find project root('.git/','/home/arch/.SpaceVim/autoload/SpaceVim/commands.vim'):/home/arch/.SpaceVim/.git/
[ SpaceVim ] [00:16:35] [ Info ] change to root:/home/arch/.SpaceVim
[ SpaceVim ] [00:16:35] [ Info ] change to root:/home/arch/.SpaceVim
```

### PR DESCRIPTION
**Pull request by MrQubo**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

Fixes #2012

### CODE REVIEW

**Comment by wsdjeg** [comment]
`execute()` need vim7.4.2008, it is too new, and in ubuntu 16.04 it is 7.4.1689, so I think use `redir` is better.

**Comment by MrQubo** [comment]
I've used `0verbose` to execute the command with the verbose set to 0.
Changed `:redir` to `execute()`, `0verbose` seems to not suppress all verbose messages when used with `:redir`.

**Comment by MrQubo** [comment]
@wsdjeg 
I'll try to make it work with `:redir` than. As the last resort we can set verbose to 0 temporarily, as you have suggested, but I would like to avoid that.

**Comment by wsdjeg** [comment]
@MrQubo I am ok with this PR, but in SpaceVim, we have provide `vim#compatible` API. and it has been loadded in guide.vim.

line:15:

```
let s:CMP = SpaceVim#api#import('vim#compatible')
```

so maybe just simply use:

```
0verbose let readmap = s:CMP.execute('map ' . key, )
```

**Comment by wsdjeg** [comment]
Merged, thanks, :) :+1:

**Pull request merged**
