### PR TITLE
Add mappings for git blame and git log

### PR DESCRIPTION
**Pull request by crisidev**

### CODE REVIEW

**Comment by wsdjeg** [comment]
for git log,

I think the existing mappings `SPC g v` and `SPC g V` is better, it use https://github.com/cohama/agit.vim

**Comment by crisidev** [comment]
@wsdjeg I did not noticed it.. Sorry about that. Would you like to keep the git blame shortcut?

**Comment by wsdjeg** [comment]
I am ok. but you can not use `Gina blame`, maybe it should be `Gina blame :`

**Comment by lambdalisue** [comment]
> I am ok. but you can not use Gina blame, maybe it should be Gina blame :

Recently it changed. So `:Gina blame` is OK for now.

https://github.com/lambdalisue/gina.vim/commit/7358ccabe6c21b934aa597506747313576a5d045

**Comment by wsdjeg** [comment]
Thanks for all of your work.

**Pull request merged**
