### PR TITLE
Denite ui

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by xiaozhu1337** [comment]
this request solves my problem
https://github.com/SpaceVim/SpaceVim/issues/2863

**Review by xiaozhu1337 — COMMENTED** [review]
https://github.com/SpaceVim/SpaceVim/issues/2863
solves some unknown function error ,but still have other error
E21: Cannot make changes, 'modifiable' is off

**Comment by Shougo** [comment]
> solves some unknown function error ,but still have other error
> E21: Cannot make changes, 'modifiable' is off

I think you have not read the documentation in denite.

https://github.com/Shougo/denite.nvim/blob/master/README.md

Note: Denite.nvim does not define any of default mappings.  You need to define
them.

https://github.com/Shougo/denite.nvim#examples

**Comment by Cosss7** [comment]
The PR works perfectly for me. What blocks it to be merged?

**Comment by wsdjeg** [comment]
the key binding do not work.

**Comment by Cosss7** [comment]
Could you describe a little detail? I hope I can do a favor.

**Comment by barkanido** [comment]
ping. any updates?

**Comment by Cosss7** [comment]
> ping. any updates?

https://github.com/SpaceVim/SpaceVim/issues/2881 there is a workaround.

**Comment by wsdjeg** [comment]
merged in #3058

**Pull request closed without merging**
