### PR TITLE
Travis: set -e with script blocks

### PR DESCRIPTION
**Pull request by blueyed**
This makes it fail actually if there are any errors.

### CODE REVIEW

**Comment by blueyed** [comment]
You can see here that vimlint is actually failing, but it was not caught.

Side note: for Travis it should exit with 1 to cause a ailure, anything else (like this) is an error.
Errors are meant for when something in the setupp failed, but this should be a failure.

**Comment by wsdjeg** [comment]
vimlint-errors is failed. the log is:

```
1Vim(let):E132: Function call depth is higher than 'maxfuncdepth'
```

I will have a look tonight.

**Comment by wsdjeg** [comment]
@blueyed this is due to there are too many vim files, we need to split the command.
issue is opened here : https://github.com/syngan/vim-vimlint/issues/107

**Comment by blueyed** [comment]
You could only run it for changed files - reminded me of https://github.com/neomake/neomake/pull/1651 (see the old `travis_lint` in there).

**Pull request merged**
