### PR TITLE
Add 3 new keybindings begining with <Leader> to meet the documentation.

### PR DESCRIPTION
**Pull request by xylinkun**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

Users may use these 3 key bindings in a normal model probably.

### CODE REVIEW

**Comment by wsdjeg** [comment]
leader y is only for visual mode.

**Comment by xylinkun** [comment]
> leader y is only for visual mode.

Why?
Vimer used to copy everything in normal mode.

**Comment by wsdjeg** [comment]
Because `"+y` in normal mode just do nothing, and it only switch into operate mode.

**Comment by xylinkun** [comment]
> Because `"+y` in normal mode just do nothing, and it only switch into operate mode.

Then, "d, c, y" do nothing either but switch into operate mode. Do you agree?

**Comment by wsdjeg** [comment]
yeah, but these key binding is not used for normal mode.

**Pull request closed without merging**
