### PR TITLE
Online tutor for SpaceVim

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

I want to write something how how to using vim as IDE, of cause it is based on SpaceVim.

### CODE REVIEW

**Comment by wsdjeg** [comment]
jump-test

**Comment by wsdjeg** [comment]
run-main

**Comment by wsdjeg** [comment]
format-java

**Comment by wsdjeg** [comment]
repl-java

**Comment by awkj** [comment]
how to install release version, I use `curl -sLf https://spacevim.org/install.sh | bash` always install dev version

**Pull request merged**
