### PR TITLE
Add test layer

### PR DESCRIPTION
**Pull request by Fetz**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]
This layer allow to run easily tests without getting out of Vim.

I used as example this commit: https://github.com/SpaceVim/SpaceVim/commit/afcf9067dc47b20c4e3fbb0bb2d4ec00e51b5e44

Related issues: https://github.com/SpaceVim/SpaceVim/issues/2099, https://github.com/janko-m/vim-test/issues/316 

# Done
- [x] add English docs test layer
- [x] add on English list layer docs, the test layer
- [x] add to doc/SpaceVim.txt the new layer
- [x] add layer to autoload/SpaceVim/layers the test.vim layer

# Missing
- [ ] add Chinese docs test layer
- [ ] add on Chinese list layer docs, the test layer

### CODE REVIEW

**Comment by wsdjeg** [comment]
I have tried this layer. 

1. why vim-test use `:!cmd` instead of job API. Maybe I will fork this plugin. and make some changes. an option for change how test is runner and how to diaplay stdout will be better. 

2. instead of changing statusline, provide a statusline API will be better.

**Comment by Fetz** [comment]
@wsdjeg thanks for trying the layer.

Regarding the point 1,2 I can't answer those questions since I'm neither a contributor/collaborator of `vim-test` and as well I'm not so knowledgable with Vim/NeoVim at the moment, maybe in the future :).

I think would be better to ask those questions on their [repo issues](https://github.com/janko-m/vim-test/issues).

If you fork and for some reason it can't go to the upstream, I can change it to point to your plugin instead.

By the way, one thing that I wanted to have (still looking for some good alternative) is a tool to alternate between code and the tests. I tried to use https://github.com/uptech/alt but it wasn't working for all the cases. There are some similar plugins or possible solutions on this stackoverflow https://stackoverflow.com/questions/9400966/is-there-a-vim-plugin-for-ruby-which-provides-a-switch-to-from-test-command-ou but they don't look ideal or limited to only ruby

**Comment by wsdjeg** [comment]
@Fetz SpaceVim has already include this plugin https://github.com/tpope/vim-projectionist

with this plugin, you can manager the your project via `.projections.json` in the root of your project.

after that, you can use command `:A` to jump between src and test file.

**Comment by Fetz** [comment]
@wsdjeg I could add a new mapping to this layer if makes sense

 | Mode    |     Key     |    Description                            |  Function    |
 | ------- | --------- |------------------------------| ----------- |
 | normal |   SPC k t  |   toggle between test and implementation  | `:A`            |

**Comment by wsdjeg** [comment]
we have already provide key binding for this feature as I know, it should be `SPC j a` in current version of SpaceVim.

I want to release v0.9.0 in one mouth, I am not sure if we should merged this layer before this release, as I need to rewrite some api of vim-test.

**Comment by wsdjeg** [comment]
can you fix the conflictiong files? I will merge this PR.

**Comment by wsdjeg** [comment]
Thanks.

**Comment by Fetz** [comment]
You welcome!

**Pull request merged**
