### PR TITLE
Fix Gabirel/Hack-SpaceVim#36

### PR DESCRIPTION
**Pull request by Gabirel**
# PR Prelude

Thank you for working on SpaceVim! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood SpaceVim's [CONTRIBUTING][cont] document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT][code] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

Fix 404 issue

### CODE REVIEW

**Review by wsdjeg — COMMENTED** [review]
why add base url? jekyll can do it automatically.

**Comment by Gabirel** [comment]
deepin-screen-recorder_select area_20180314170520

**Comment by wsdjeg** [comment]
Ok， I will look into it.

**Comment by wsdjeg** [comment]
@Gabirel Just change `(documentation/)` to `(documentation)` will fix this issue.

**Comment by Gabirel** [comment]
This issue still exists. Please try to consider changing it into the full URL path. It could keep the same document style.

**Comment by wsdjeg** [comment]
@Gabirel We can not use full URL path in markdown file, because when you test the website locally, the URL is looks like `https://127.0.0.1:4000/Documentation/`, so you can not use full path.

and I ust check it website, I can not find the 404 page, where is it? maybe you need to clear the cache.

**Comment by wsdjeg** [comment]
Fixed.

**Comment by Gabirel** [comment]
- Yes, it's fixed in `spacevim.org`. But that doesn't fix 404 when trying to click the link in github.

- According to here:
https://github.com/SpaceVim/SpaceVim/edit/master/docs/development.md#50
```md
- [SpaceVim documentation](https://spacevim.org/documentation): It is the general documentation of SpaceVim.
```

This file is using the full URL as well. That's why I recommend this one since it can fix all issues

**Comment by wsdjeg** [comment]
What is the page you get 404?

**Comment by wsdjeg** [comment]
@Gabirel the dir `docs/` is only for the website, not for the github page, user should not click it in github, because we use many jekyll stuff.

such as in index.md

```
<ul>
    {% for post in site.categories.feature offset: 0 limit: 5  %}
               <strong><a href="{{ post.url }}">{{ post.title }}</a></strong>
               <br>
               <span class="post-date">{{ post.date | date_to_string }}</span>
               <p>{{ post.excerpt | truncatewords: 100 }}</p>
               <br>
               <img alt="{{ post.title }}" src="{{ post.image }}">
    {% endfor %}
</ul>

```

this can not be pasered in github, but it works well in website.

and I will remove all full URL which is `spacevim.org` in the `docs/`. the base url is definded in `_config.yml`

```
url: https://spacevim.org
```

**Comment by wsdjeg** [comment]
you can read https://github.com/SpaceVim/SpaceVim/blob/master/docs/index.md

this page is not readable in github, but it works well in website.

**Pull request closed without merging**
