### PR TITLE
Add keybinding for resize defx

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### CODE REVIEW

**Comment by wsdjeg** [comment]
@Shougo thanks for update defx to support resize feature. I have two key bindings in defx config:

```
  nnoremap <silent><buffer><expr> > defx#do_action('resize', winwidth(0) + 10)
  nnoremap <silent><buffer><expr> < defx#do_action('resize', winwidth(0) - 10)
```

when open defx, if the file name is too long, I see `xxxx.....xxxx.txt` in the defx buffer. the if I press `>` I can see the whole file name. but if then I press `<` again, the column after file is hidden, and the file name is still `xxxxxxxxxxxxxxx.txt`, it should be changed to `xxxx...xxxx.txt` again.

**Comment by Shougo** [comment]
```vim
	nnoremap <silent><buffer><expr> > defx#do_action('resize',
	\ defx#get_context().winwidth + 10)
	nnoremap <silent><buffer><expr> < defx#do_action('resize',
	\ defx#get_context().winwidth - 10)
```

**Comment by wsdjeg** [comment]
Thanks! But it seems do not work, I see following red message:

```


[defx] 30
[defx] 40
[defx] 40
[defx] 40
[defx] 40
[defx] 50
[defx] 50
[defx] 50
[defx] 50
[defx] 60
[defx] 60
[defx] 60
[defx] 60
[defx] 50
[defx] 50
[defx] 50
[defx] 50
[defx] 40
[defx] 40
[defx] 40
[defx] 40
[defx] 30
[defx] 30
[defx] 30
[defx] 30
[defx] 20
[defx] 20
[defx] 20
[defx] 20
[defx] 10
[defx] 10
[defx] 10
[defx] 10
[defx] 0
[defx] 0
[defx] 0
[defx] 0
[defx] -10
[defx] -10
[defx] -10
[defx] -10
[defx] 0
[defx] 0
[defx] 0
[defx] 0
[defx] 10
[defx] 10
[defx] 10
[defx] 10
[defx] 20
[defx] 20
[defx] 20
[defx] 20
[defx] 30
[defx] 30
[defx] 30
[defx] 30
[defx] 40
[defx] 40
[defx] 40
[defx] 40
[defx] 50
[defx] 50
[defx] 50
[defx] 50
[defx] 60
[defx] 60
[defx] 60
[defx] 60
[defx] 70
[defx] 70
[defx] 70
[defx] 70
[defx] 60
[defx] 60
[defx] 60
[defx] 60
[defx] 50
[defx] 50
[defx] 50
[defx] 50
[defx] 40
[defx] 40
[defx] 40
[defx] 40
[defx] 30
[defx] 30
[defx] 30
[defx] 30
[defx] 20
[defx] 20
[defx] 20
[defx] 20
[defx] 10
[defx] 10
[defx] 10
[defx] 10
[defx] 0
[defx] 0
[defx] 0
[defx] 0
[defx] 10
[defx] 10
[defx] 10
[defx] 10
[defx] 20
[defx] 20
[defx] 20
[defx] 20
[defx] 30
[defx] 30
[defx] 30
[defx] 30
[defx] 40
[defx] 40
[defx] 40
[defx] 40
[defx] 50
[defx] 50
[defx] 50
[defx] 50
[defx] 60
[defx] 60
[defx] 60
[defx] 60
```

**Comment by Shougo** [comment]
@wsdjeg Please update defx.  I have removed the messages.

**Comment by wsdjeg** [comment]
@Shougo I have update defx, but the `< defx#do_action('resize', 	defx#get_context().winwidth - 10)` do not decrease the width of filename.

**Comment by Shougo** [comment]
Really?
It does work for me.
Please create the new issue without SpaceVim.

**Comment by wsdjeg** [comment]
the mini virmc

```vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/defx.nvim
call defx#custom#option('_', {
      \ 'winwidth': 30,
      \ 'split': 'vertical',
      \ 'direction': 'rightbelow',
      \ 'show_ignored_files': 0,
      \ 'buffer_name': '',
      \ 'toggle': 1,
      \ 'resume': 1
      \ })

call defx#custom#column('mark', {
      \ 'readonly_icon': '',
      \ 'selected_icon': '',
      \ })

call defx#custom#column('icon', {
      \ 'directory_icon': '',
      \ 'opened_icon': '',
      \ 'root_icon': ' ',
      \ })
augroup vfinit
  au!
  autocmd FileType defx call s:defx_init()
augroup END
endfunction

function! s:defx_init()
    nnoremap <silent><buffer><expr> > defx#do_action('resize',
	\ defx#get_context().winwidth + 10)
	nnoremap <silent><buffer><expr> < defx#do_action('resize',
	\ defx#get_context().winwidth - 10)
endf
```


step:

1. `:e docs\_posts\2017-02-20-install-vim-or-neovim-with-python-support.md`
2. run :

```
Defx  -no-toggle -search=`expand('%:p')` `stridx(expand('%:p'), getcwd()) < 0? expand('%:p:h'): getcwd()`
```

3. the the file name is show as `2017-02-20-instal....on-support.md`

4. press `>`, I only add 10 to winwidth, but the whole file name is shown

5. press `<`, still whole file name is shown, it should same as before.

**Comment by Shougo** [comment]
Please read this.

https://github.com/Shougo/defx.nvim/issues/164#issuecomment-533748997

**Comment by Shougo** [comment]
You need to configure filename column.

**Comment by wsdjeg** [comment]
@Shougo Thanks, all things have been done.

**Pull request merged**
