### PR TITLE
Improve scheme layer

### LINKED ISSUE #3298: Support Chez Scheme dialect
**What is language?**

lang#scheme

**Which platform does the language support?**

- [x] windows
- [x] Mac os
- [x] Windows

**Any suggest vim plugins for this language?**

No

**Additional context**

[Chez Scheme](https://cisco.github.io/ChezScheme/) is a Scheme dialect by Cisco Inc.  Its executable named 'scheme' at Windows, but named 'chez' at HomeBrew.  Because SpaceVim doesn't support conditional layer option, it prevents  one ``init.toml`` to be used at two OS.

### PR DESCRIPTION
**Pull request by wsdjeg**
close #3298 

Whit this PR, users can config the scheme layer via:

```
[[layers]]
    name = 'lang#scheme'
    scheme_interpreter = 'C:\Program Files\Chez Scheme 9.5\bin\ta6nt\scheme.exe'
```

### Chez Scheme support

**REPL**

chez scheme repl

**Code runner**

Chez Scheme runner

### CODE REVIEW

**Comment by thawk** [comment]
This solution doesn't seem to work with the HomeBrew version of Chez Scheme.
1. The executable file of Chez Scheme in HomeBrew is ``/usr/local/bin/chez``, I don't think it can match with ``Chez Scheme``.
2. The interpreter of other two dialect is basename, so it's better to config Chez Scheme with basename instead of full path.
3. Chez Scheme doesn't support ``--silent`` parameter.  It supports a ``--quiet``.  BTW, I check the manual of mit-scheme and guile, but I can't found the ``--silent`` parameter, maybe it's a typo?
4. Maybe the combine of original ``dialect`` option, and additional ``runner_option``/``repl_option`` can be a better solution?  Because the options required by the runner and by the repl are different (e.g. ``--scripts %s`` for runner, ``--quiet %s`` for repl).

**Comment by wsdjeg** [comment]
@thawk 

1. change the expr to `=~? 'chez'` , then both `chez` and `Chez` will be matched.

**Comment by thawk** [comment]
I don't know what's the executable name in all other OS, like different Linux distro. Maybe they use ``/usr/bin/scheme`` as in ArchLinux([PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chez-scheme)). So it can't match anything about ``chez``.
I want to have a solution to share the config between different computers. I use the same configuration between Windows/MacOS/Linux/FreeNAS and the executable paths  are different between them.

**Comment by wsdjeg** [comment]
>  I want to have a solution to share the config between different computers. 

support conditional layer option will be done in next release, before this is done, you need to use bootstrap function to config the layer.

**Comment by wsdjeg** [comment]
> Maybe they use /usr/bin/scheme as in ArchLinux(PKGBUILD).
@thawk This is not officail package,  it is aur package.

**Comment by thawk** [comment]
> > Maybe they use /usr/bin/scheme as in ArchLinux(PKGBUILD).
> > @thawk This is not officail package,  it is aur package.

[Ubuntu](http://manpages.ubuntu.com/manpages/bionic/man1/chezscheme9.5.1.html) uses ``scheme`` too.

**Comment by thawk** [comment]
> 》 I want to have a solution to share the config between different computers.
> 
> support conditional layer option will be done in next release, before this is done, you need to use bootstrap function to config the layer.

It's good to know it.  Should I using my ``autocmd FileType scheme`` to override the runner and repl? Or do I miss something?

**Comment by wsdjeg** [comment]
No, just using following snippet in bootstrap after function.

```
if  .....
       call SpaceVim#plugins#runner#reg_runner('scheme', '.....')
       call SpaceVim#plugins#repl#reg('scheme', '....')
else
       call SpaceVim#plugins#runner#reg_runner('scheme', '.....')
       call SpaceVim#plugins#repl#reg('scheme', '....')
endif

```

**Pull request merged**
