### PR TITLE
Add floobits layer

### PR DESCRIPTION
**Pull request by wsdjeg**
# PR Prelude

Thank you for working on SpaceVim! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [ ] I have read and understood SpaceVim's [CONTRIBUTING][cont] document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT][code] document.
- [ ] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [ ] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]

[cont]: https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md
[code]: https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by emaxerrno** [comment]
any timeline on this. no pressure at all, just wondering. thanks!!

**Comment by emaxerrno** [comment]
i just tested this by removing ~/floobits, pulling the latest tag, and starting vim again and the folder ~/floobits  is still there. FYI.

**Comment by emaxerrno** [comment]
https://gist.github.com/49d51c8969c00701bbf4bf875770b7cb

**Comment by emaxerrno** [comment]
I'm at this spacevim hash @wsdjeg  7f0723e93e764403fa6eaf89740e01a53643a794

**Comment by wsdjeg** [comment]
you need to update remote plugins

**Comment by emaxerrno** [comment]
:UpdateRemotePlugins
```
remote/host: python3 host registered plugins []                                                                                                                                                               
remote/host: generated rplugin manifest: /home/agallego/.local/share/nvim/rplugin.vim 
```

Stop and restart vim and i still see ~/floobits

**Comment by emaxerrno** [comment]
@wsdjeg any other tips?

**Comment by emaxerrno** [comment]
nvm. i just pulled master again - right now - and this time it worked after :UpdateRemotePlugins call

**Comment by wsdjeg** [comment]
please use new issue.

**Pull request merged**
