### PR TITLE
Add layer option for git layer

### LINKED ISSUE #2563: Possibility to use fugitive as git layer main plugin
AFAICT, fugitive is the best known git plugin. Is there any reason why it isn't used in the git layer?

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

close #2563

### CODE REVIEW

**Comment by chenlijun99** [comment]
Hi, what is stopping this from being merged? Can I give a hand?

**Comment by wsdjeg** [comment]
the implementation of fugitive is different, I need to test it more.

**Comment by theutz** [comment]
Thanks for making this change! How would I go about implementing in this in my own `init.toml`? I've tried the following approaches and nothing changes:

```
[options]
git_plugin = 'fugitive'
```

```
[[layers]]
name = 'VersionControl'
git_plugin = 'fugitive'
```

```
[[layers]]
name = 'git'
git_plugin = 'fugitive'
```

Thanks in advance!

**Comment by wsdjeg** [comment]
it should be:

```toml
[[layers]]
   name = "git"
   git-plugin = "fugitive"
```

**Comment by theutz** [comment]
Awesome! That works great!

**Pull request merged**
