### PR TITLE
feat(lang#c): add `SPC l g` to go to definition

### PR DESCRIPTION
**Pull request by sisrnb**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?
It's better to provide a shortcut to go to definition after user has pressed `SPC l` while editing c files. This is because the menu of `SPC l` has `declaration` but doesn't have `definition`, and `implementation` doesn't work with clangd.

### CODE REVIEW

**Comment by wsdjeg** [comment]
@sisrnb for many languages layer, we use `g d` to jump to definition. and this key binding is available in `lang#c` layer.

**Comment by sisrnb** [comment]
The menu of `SPC l` has `declaration` but doesn't have `definition`, the user goes here may want to go definition but there is not such an entry.
And `implementation` doesn't work with clangd.
And many language layers have shortcut `SPC l g`.
Also I personally think some consistency should be made between language layers.

**Comment by sisrnb** [comment]
I was confused when I'm new to SpaceVim, I was wondering why `SPC l i` can not go to definition.

**Comment by wsdjeg** [comment]
Maybe we should unify all these key bindings for different languages. maybe `g` is better for  `+Generate` group key bindings.

in development page: https://spacevim.org/development/#language-specified-key-bindings

**Comment by sisrnb** [comment]
`lang#c` seems lack of maintenance, `SPC l i` (go to implementation) has no action c files.
I'm using clangd, I haven't tested any other c language server.

**Comment by wsdjeg** [comment]
yeah, currently I am too busy, we also want to looking for contributors for each language layer. I will update the `lang#c` layer and doc.

**Pull request closed without merging**
