### PR TITLE
Fix coc.nvim installation.

### PR DESCRIPTION
**Pull request by tjni**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

The installation scripts for coc.nvim have been removed.

### CODE REVIEW

**Comment by wsdjeg** [comment]
so why can not use master branch?

**Comment by tjni** [comment]
No strong reason. The release branch was what was recommended in the coc.nvim README, but pulling from master works as well. Please let me know which you prefer.

**Comment by wsdjeg** [comment]
we should use `yarn install --frozen-lockfile` instead.

**Comment by tranhoangcore** [comment]
#3540

**Comment by tjni** [comment]
I tested using the `yarn` command, and I don't like that it doesn't work if `yarn` isn't installed. It also requires a build step each time coc.nvim is updated. For those reasons, I prefer keeping it on the release branch, which includes a pre-built `build` directory. What do you think?

This does require updating the plugin installation logic to switch branches properly, which I've changed in the latest commit.

**Comment by Guzzii** [comment]
This is awesome. I was going to make the same PR.

@tjni But for some reason, it would not work by simply using the release like this `{'merged': 0, 'rev': 'release'}`. It would throw an error saying `javascript file not found`. The only way that works for me right now is to build from source with `{'merged':0, 'build': 'yarn install --frozen-lockfile'}`

**Comment by tjni** [comment]
@Guzzii 

Would you be able to try with the most recent commit? It has a few additional lines updated that I expect to fix issues related to using `rev`. If it doesn't work, we can work on narrowing down where the problem is.

**Comment by Guzzii** [comment]
> @Guzzii
> 
> Would you be able to try with the most recent commit? It has a few additional lines updated that I expect to fix issues related to using `rev`. If it doesn't work, we can work on narrowing down where the problem is.

Yep @tjni. I will try to give it shot today once I get some free time.

**Comment by wsdjeg** [comment]
The release branch history is not same as the master branch, I just check the gitlog of coc, I think the most safe way to use this plugin is use build command. I will update the coc build command.

**Comment by wsdjeg** [comment]
merged in 3564

**Pull request closed without merging**
