### PR TITLE
Fix toggle show tail spaces

### LINKED ISSUE #2079: The tail spaces in prompt window are shown red when the option "Show white space" is opened.
The tail spaces in prompt are shown red when the option "Show white space" is on.
I think the function "show the tail spaces" is short of the judgment whether the tail spaces is in the prompt window.

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

close #2079

### CODE REVIEW

**Comment by xylinkun** [comment]
Is it able to disable the function "highlight tail spaces" working in the startify page? although it's boring that someone opens the option "highlight tail spaces" in the startify page.

**Comment by wsdjeg** [comment]
I have disabled it.

**Comment by xylinkun** [comment]
It still work on the page startify on my computer!
I have add "startify" to the blacklist just like you add "leaderGuide" to the blacklist. But it still work on the startify page.

**Comment by wsdjeg** [comment]
I can not reproduce it, I think you need to post more info, what is your spacevim version, and what is `git status` in `~/.SpaceVim`.

and what is `git log -n1` in `~/.SpaceVim`

**Comment by xylinkun** [comment]
`linkun@HP-Z230-SFF MINGW64 /c/Users/linkun/.SpaceVim (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    config/plugins/asyncomplete.vim

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        config/plugins/asyncomplete.vim

no changes added to commit (use "git add" and/or "git commit -a")

linkun@HP-Z230-SFF MINGW64 /c/Users/linkun/.SpaceVim (master)
$ git log -n1
commit ce23ca96be7891c83823c1891d8139c2d8297cde (HEAD -> master, origin/master, origin/HEAD)
Author: Wang Shidong <wsdjeg@outlook.com>
Date:   Fri Aug 24 21:30:49 2018 +0800

    Fix toggle show tail spaces (#2080)

    * Fix toggle show tail spaces

    * Disable tial space for startify

    * Update wiki

linkun@HP-Z230-SFF MINGW64 /c/Users/linkun/.SpaceVim (master)
$
`

**Comment by wsdjeg** [comment]
ok, I reopen that issue, and I will try to fix it.

**Comment by xylinkun** [comment]
Thank you.

**Pull request merged**
