### PR TITLE
Fixed: refactor fzf layer with 'fzf.vim'

### PR DESCRIPTION
**Pull request by wy-z**
Signed-off-by: weiyang <weiyang.ones@gmail.com>

### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

https://github.com/junegunn/fzf.vim is good enough ~

### CODE REVIEW

**Comment by wsdjeg** [comment]
sorry, I do not want to included fzf.vim, as it is just a wrapper of fzf, which can be done in this layer simplly, and easy for debug.

**Comment by wsdjeg** [comment]
also see #1725

**Comment by wy-z** [comment]
Uh...but I think https://github.com/junegunn/fzf.vim is good enough, and there are so many code were copied from it

**Comment by wy-z** [comment]
If you think it is not good enough, you could try to improve it ~
https://github.com/junegunn/fzf.vim was created by `junegunn`, I think he has more time and ability to guarantee the quality of it

**Comment by wsdjeg** [comment]
```
fzf in itself is not a Vim plugin, and the official repository only provides the basic wrapper function for Vim and it's up to the users to write their own Vim commands with it. However, I've learned that many users of fzf are not familiar with Vimscript and are looking for the "default" implementation of the features they can find in the alternative Vim plugins.

This repository is a bundle of fzf-based commands and mappings extracted from my .vimrc to address such needs. They are not designed to be flexible or configurable, and there's no guarantee of backward-compatibility.
```
**it's up to the users to write their own Vim commands with it.**, I think we should implement the command in SpaceVim. that will be easy to debug.

**Comment by wy-z** [comment]
I like `SpaceVim` and I think it is an excellent distribution, but I think it should focus on organization but not try to warp every thing ~

**Comment by wsdjeg** [comment]
If you really like to use fzf.vim, maybe you can create a private layer in your SpaceVim config. for example

`~/.SpaceVim.d/autoload/SpaceVim/layer/anotherfzf.vim`

then enable the layer in your toml file

```toml
[[layers]]
    name = 'anotherfzf'
```

**Comment by wsdjeg** [comment]
SpaceVim has 5 fuzzy find layer, we need to key compatible with other 4 fuzzy finder layer, fzf.vim do not support hard config, as it says in readme `They are not designed to be flexible or configurable`.

in SpaceVim, if we can implemnet the feature, I do not want to use third_part plugins. 

why?

for example, in old version of SpaceVim, we use vim-rooter for detect the project root directory, but that plugin has some bugs, and the author do not want to fix it, But I need to use the feature. so How could I do? I reimplement a new project manager plugin.

**Comment by wy-z** [comment]
Thanks, I will ~

**Comment by wy-z** [comment]
And there are some problems with the current fzf layers ~

**Comment by wsdjeg** [comment]
@wy-z SpaceVim provide an idea of how to manager plugins and config, dark vim user should has there own private layer, for example my record layer provides feature for recording gif in vim.

yeah,

> And there are some problems with the current fzf layers ~

yeah, that should be fixed. just same as #1725

**Comment by wy-z** [comment]
- https://github.com/SpaceVim/SpaceVim/blame/master/autoload/SpaceVim/layers/fzf.vim#L36 
If I want to`jump to a definition in buffer` I have to install `denite` layer
- `FzfOutline` doesn't work well in my environment, see ~
image

**Comment by wy-z** [comment]
`FzfOutline` has so many useless blank lines in output ~

**Comment by wy-z** [comment]
`BTags` works well~
image

**Comment by wy-z** [comment]
https://github.com/SpaceVim/SpaceVim/blame/master/autoload/SpaceVim/layers/fzf.vim#L267
Why do you rewrite these codes? https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L239 works fine ~

**Comment by wy-z** [comment]
@wsdjeg Thank you for your contribution on `SpaceVim` ~
I personally think https://github.com/junegunn/fzf.vim is acceptable ~ it is not the core dependency of `SpaceVim`, but a supplementary layer~
You can close the PR if you want~
Thanks again ~

**Comment by wsdjeg** [comment]
Ok, thanks, :)

**Pull request closed without merging**
