### PR TITLE
Add: introduce php lsp key bindings

### PR DESCRIPTION
**Pull request by gbprod**
### PR Prelude

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

In [this PR](https://github.com/SpaceVim/SpaceVim/pull/3920), we introduce a new PHP LSP server. This PR adds key bindings for many task that phpactor can do for refactoring/managing php code.

### CODE REVIEW

**Comment by wsdjeg** [comment]
What is the differences between this plugin as vim-lsp or language-client.nvim? does it support deoplete?

**Comment by gbprod** [comment]
[PhpActor](https://phpactor.readthedocs.io/) is not a plugin to add support of LSP in vim/neovim, it's a completion and refactoring tool for PHP. 

It provides a Language Server that seems to be the best LSP server for php today.

It also provides a lot of refactoring tools that are not currently available with LSP (eg. using CodeActions) but using [RPC calls from his vim plugin](https://phpactor.readthedocs.io/en/develop/usage/vim-plugin.html) 

What I suggest here is to add shortcuts to those features.

However, it seems that the author of phpactor will implements those features with codeactions, so I think I will create a PR to add LSP CodeActions support with Coc and maybe close this PR.

**Comment by gbprod** [comment]
Is there a way to add these key bindings just for me, without changing the php layer ? I couldn't find the information in the documentation.

**Comment by gbprod** [comment]
I've made it using `autocmd`, you can close this PR if you don't think it's relevant for SpaceVim.
(And thanks for your work, it's amazing)

**Comment by wsdjeg** [comment]
Ok, thanks for your work.

**Pull request closed without merging**
