### PR TITLE
Add new interesting banners

### PR DESCRIPTION
**Pull request by Gabirel**
# PR Prelude

Thank you for working on SpaceVim! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood SpaceVim's [CONTRIBUTING][cont] document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT][code] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]
Add more interesting banners into SpaceVim to make vimmer more happier

[cont]: https://github.com/SpaceVim/SpaceVim/blob/dev/CONTRIBUTING.md
[code]: https://github.com/SpaceVim/SpaceVim/blob/dev/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by wsdjeg** [comment]
@Gabirel Please use `SpaceVim` only, and long text will not be shown if the screen is too small.

**Comment by Gabirel** [comment]
why is `SpaceVim` only? That would be too boring though. The fact is that you won't get too many new banners if you stick to the `SpaceVim` only.

Some are quite small. But I really don't think people who are using vim with 80x24 window don't really need the banner at all since they just need vim to edit a file only in a little small window. After that, they just close vim. They will switch vim into bigger size if they really want to code. Don't you think so?

**Comment by Gabirel** [comment]
Oh, if you think which banner is inappropriate tell me to delete it. Please accept the banner which is not `SpaceVim`

**Comment by wsdjeg** [comment]
OK, I will look into it. We should keep width <  150.

**Comment by Gabirel** [comment]
I've tested them all. The max of banners can be displayed within 150 window. Here's the screenshot:
screenshot_2017-12-31_13-50-45

**Pull request merged**
