### PR TITLE
Fixed loading config file

### PR DESCRIPTION
**Pull request by michaeladler**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by michaeladler** [comment]
Just for the record, I don't believe my changes cause vimlint to break. It appears to me that b362f23beceb33ddd56bb7eafba1aa25fe0fc14f is responsible for that, introducing the function ` SpaceVim#custom#write(force)` with an empty body, i.e. the argument  `force` is unused and that's what vimlint complains about.

**Comment by wsdjeg** [comment]
Thanks For your pr. what is the issue? I can not reproduce it in current version.

**Comment by michaeladler** [comment]
The line `exe 'let g:spacevim_' . name . ' = value'` expands to `let g:spacevim_<name> = value`, where `name` is the only variable in that expression. In other words, you set the value of each option to the string "value". So, if you attempt to set any options in your `init.toml`, it will silently fail because the actual value of the variable is ignored. This is a quite serious bug.

**Comment by wsdjeg** [comment]
seems strange, but it works well for me. I will test it.

**Comment by wsdjeg** [comment]
@michaeladler I have use the master branch everyday, but I can not reproduce this issue, can you provide any reproduce step?  for example

```toml
[options]
   filemanager = "nerdtree"
```

then open vim, run `:echo g:spacevim_filemanager`, I think you should see `nerdtree`.

**Comment by wsdjeg** [comment]
I just look into this issue, with this config:

```toml
[options]
   filemanager = "nerdtree"
```

SpaceVim will run:

```vim
let [key, value] = ['filemanager', 'nerdtree']
exe 'let g:spacevim_' . name . ' = value'
```

let last line means:

```
exe 'let g:spacevim_filemanage = value'
```

which is same as

```
let [key, value] = ['filemanager', 'nerdtree']
let g:spacevim_filemanage = value
```

**Pull request closed without merging**
