### PR TITLE
Change plugin

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by alanding1989** [comment]
command **Translate** need arguments

> ### PR Prelude
> Thank you for working on SpaceVim! :)
> 
> Please complete these steps and check these boxes before filing your PR:
> 
> * [ ]  I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
> * [ ]  I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
> * [ ]  I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.
> 
> ### Why this change is necessary and useful?
> [Please explain **in detail** why the changes in this PR are needed.]

command **Translate** need arguments <word>,  could you please also add a keybinding to let user input **specific word** to translate:
> `call SpaceVim#mapping#space#def('nmap', ['x', 'g', 'i'], 'call feedkeys(":TranslateW ")', 'translate input word or sentence', 1)`
something like this. if without call feedkeys, command line doesn`t had any hints to show.

**Comment by wsdjeg** [comment]
new version of vtm support empty argv.

**Comment by alanding1989** [comment]
> new version of vtm support empty argv.

you need to update your forked repo .

**Comment by wsdjeg** [comment]
@alanding1989 yeah, I have changed the repo to remote repo.

**Pull request merged**
