### PR TITLE
make luaer happy :D && make molokai support spell check

### PR DESCRIPTION
**Pull request by Gabirel**
- make luaer happy :D 
- adjust sequence
- let molokai supports spell check

### CODE REVIEW

**Comment by Gabirel** [comment]
What about other colorschemes that can't show the word with spell errors?

**Comment by wsdjeg** [comment]
I prefer send PR to these colorshemes repo thought, I have no much time to maintainer these color repo.

**Comment by Gabirel** [comment]
yes, of course. But I advise to point it out in your documents and tell others how to fix if anyone encounter this problem.

**Comment by wsdjeg** [comment]
ok, you add add some doc for it.

**Comment by Gabirel** [comment]
Instruction of spell check failure has been added in doc.

**Comment by Gabirel** [comment]
Please close issue #209

**Comment by wsdjeg** [comment]
Thanks.

**Pull request merged**
