### PR TITLE
Add icons and git status to defx

### PR DESCRIPTION
**Pull request by yuxiang-gao**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?
Both Vimfiler and Nerdtree have icons and git status, adding these to Defx would make the appearances of the file trees more uniform.

### CODE REVIEW

**Comment by ghost** [comment]
This PR would fix the problem that I’ve been having while trying to use a bootstrapping function to override the default columns.

**Comment by wsdjeg** [comment]
Thanks for this PR.

1. enable_vimfiler_filetypeicon and enable_vimfiler_gitstatus should be used to contrl this two colum
2. spacevim has build-in icon api, this should be used instead of defx-icon
--------------
wsdjeg

**Comment by ghost** [comment]
This PR was resolved by #3320 and should be closable.

**Comment by wsdjeg** [comment]
Ok, thanks

**Pull request closed without merging**
