### PR TITLE
Propose to add the option to set the position of the nerdtree window in init.toml

### PR DESCRIPTION
**Pull request by nikolaussucher**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [x ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

I like to have the NERDTree window on the left rather than on the right. I propose to add a global variable "nerdtree_win_pos" that can be set in init.toml to "left" or "right". I am not sure where to add the description. This addition is certainly not necessary but I find it useful and more straight forward than doing this any other way. The name of the new variable could certainly be something else if more appropriate.

### CODE REVIEW

**Comment by wsdjeg** [comment]
Hi, thanks for this PR, and we have two kind of file tree, I think maybe we should keep the option name same as each other. for example: `filetree_direction`?

and we have many kind of sidebar plugins in spacevim, maybe we should provide a option to contrl all of them:

- tha tab manager: `SPC t t`
- the tagbar: `<F2>`
- the filetree, nerdtree or vimfiler: `<F3>`
- the undotree: `<F8>`


in current version of spacevim, we only have two options:

`sidebar_width`: this option is to set the width of vimfiler and tagbar.
`g:vimfiler_direction`: this is for setting vimfiler direction.

as I know, there is a plugin winmanager.vim which can merge taglist and nerdtree together, and manybe we can rewrite this plugin, and merge tagbar and filetree together.

**Comment by wsdjeg** [comment]
and after that, the screen should looks like:

**Comment by nikolaussucher** [comment]
Ok. It sounds reasonable to have a unified way to manage sidebars. In fact, right now, the various sidebars appear to interact in a way that leads to unexpected results. 

The use of the word "direction" in relation to the location (address) of the sidebar is archaic. It will be better to use "position". It is unfortunate that vimfiler uses the former and not the latter.

**Comment by wsdjeg** [comment]
@nikolaussucher can you change the option name to `g:spacevim_sidebar_direction`? I want to merged it.

**Comment by nikolaussucher** [comment]
I changed it. Thank you!

Dr. Nikolaus Sucher
Professor
Science
Roxbury Community College
1234 Columbus Ave<x-apple-data-detectors://2/1>
Roxbury Crossing, MA 02120<x-apple-data-detectors://2/1>

Ph: (857) 701-1525‬

On Sep 14, 2018, 9:21 AM -0400, Wang Shidong <notifications@github.com>, wrote:

@nikolaussucher<https://github.com/nikolaussucher> can you change the option name to g:spacevim_sidebar_direction? I want to merged it.

**Pull request merged**
