### PR TITLE
Improve lang#r layer and doc

### LINKED ISSUE #2482: rlang layer configuration doesn't act like milestone guides
## Expected behavior, english is required
I'm interested in using the R layer but I'm not sure how to configure it accordingly to the guides posted under its addition during the 2017-2018 milestone.

## The reproduce ways from Vim starting (Required!)
View the guides and notice that autocompletion is not enabled, in terminal shell is not functional, also I'm not sure how to configure the bootstrap options.

I believe these options would enable autocompletion
`cat ~/.SpaceVim.d/autoload/myspacevim.vim
# https://www.reddit.com/r/vim/comments/93xr5g/autocomplete_omnicomplete_for_gnu_r/
# https://spacevim.org/layers/lang/python/
 
 
func! myspacevim#before() abort
    let g:R_in_buffer = 1
    let g:maplocalleader = ','
    let g:R_show_args = 1         " show the arguments for functions with autocompletion
    let g:R_args_in_stline = 0    " do not show arguments in statusline
    let g:R_in_buffer = 0         " I want R in an external terminal, because I use I3
    let g:R_assign = 0            " do not convert _ into <-, annoying!
    let g:R_insert_mode_cmds = 1  " allow R commands in insert mode
    let g:R_term_cmd = 'st -n R'  " command to execute R in my terminal , with window name R
    let g:R_clear_line = 0        " do not clear line before executing a command, sadly does not work with st
    let g:R_args = ['--no-save']  " call R with the --no-save option
    autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif     " exit R when you exit the vim
endf
 
 
func! myspacevim#after() abort
endf`

would love to help! thanks wang

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

close #2482

### CODE REVIEW

**Comment by kayfay** [comment]
Opening a REPL doesn't work
screenshot from 2019-01-24 12-11-27

**Comment by kayfay** [comment]
using \rf opens a REPL in a new window
screenshot from 2019-01-24 12-12-13

**Comment by kayfay** [comment]
switching to the R language layer breaks a few functionalities that were provided by a second stack of addons I was using from the guides posted in the r mile stone.

would it be possible to include these?

 [[custom_plugins]]
   name = "roxma/nvim-yarp"
   name = "ncm2/ncm2"
   name = "jalvesaq/Nvim-R"
   name = "gaalcaras/ncm-R"
   name = "roxma/vim-hug-neovim-rpc"
   name = "ncm2/ncm2-path"
   name = "ncm2/ncm2-bufword"

**Comment by kayfay** [comment]
A really important feature that looks like it isn't working anymore is \o which will send a command to the r console and insert the output into the code commented

**Comment by wsdjeg** [comment]
Please use new isseue for bug report and feature request, I can not get eamil for merged/closed pr and issue.

**Pull request merged**
