### PR TITLE
JavaScript layer code owner

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I have updated the [Following-HEAD](https://github.com/SpaceVim/SpaceVim/blob/master/wiki/en/Following-HEAD.md) page for this PR.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

ref: #2002

### CODE REVIEW

**Comment by wsdjeg** [comment]
@zhujinxuan @sei40kr @S1ngS1ng

Thanks for contribute to SpaceVim, and now we want to call for code owner for javascript layer, 
This new feature automatically requests reviews from the code owners when a pull request changes any owned files.

javascript layer included these files:

```
autoload/SpaceVim/layers/lang/javascript.vim
docs/layers/lang/javascript.md
docs/cn/layers/lang/javascript.md
```

**Comment by zhujinxuan** [comment]
May I know what does `code owner` mean?

**Review by zhujinxuan — DISMISSED** [review]

**Comment by zhujinxuan** [comment]
I would like to be the code owner to review the PR/issues related to javascript and typescript~

**Comment by S1ngS1ng** [comment]
I am not fully proficient with Vimscript, still I'd like to give this a shot.

**Comment by chemzqm** [comment]
I can help to review PR/issues related to javascript and typescript

**Comment by wsdjeg** [comment]
Thanks all of you, and I will update the config of js layer code owner.

**Pull request merged**
