### PR TITLE
Fix project root detection to work with empty buffer

### PR DESCRIPTION
**Pull request by agriffis**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

So that you can run "vim" in a project and use fzf to find a file.

### CODE REVIEW

**Comment by wsdjeg** [comment]
@agriffis The default logic of spacevim project detection do not skip empty buffer in old version, I do not remember why I add `skip empty buffer` feature. When start vim via `vim` in a directory, vim will call root detection function. but no file is opened, and current buffer is empty, now it can not find the root. so this is a bug.

**Comment by agriffis** [comment]
@wsdjeg Hmm, interesting. For me, when I open vim with no file, I want it to get the project root based on the working directory. Are you suggesting there's a different approach to consider?

**Comment by wsdjeg** [comment]
merged, I have test it, and we should not skip empty buffer.

**Comment by wsdjeg** [comment]
Thanks!

**Pull request merged**
