### PR TITLE
Fix OmniSharpFindType to OmniSharpTypeLookup

### PR DESCRIPTION
**Pull request by PandaLz**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]
Fix call of discontinued OmniSharpFindType to OmniSharpTypeLookup command.

### CODE REVIEW

**Comment by wsdjeg** [comment]
@PandaLz Thanks for your PR, and sorry for late reply, I do not read the code of this plugin, is `OmniSharpFindType` removed from this plugin?

**Comment by PandaLz** [comment]
@wsdjeg Hi there, no problem :) Yeah, remember OmniSharpFindType not working "Command not found" iirc, swapped with the closest alternative which is OmniSharpTypeLookup, now, being trying Coc completion for a while and just checked the current Omnishap behavior with deoplete and lsp again.

While OmnisharpFindType exist again it opens a Unite window Omnisharp/findsymbols(1) with a prompt. Tested OmniSharpTypeLookup and it behaves as expected showing they type of the object under the cursor.

**Comment by wsdjeg** [comment]
merged. thanks

**Comment by PandaLz** [comment]
Thank you!

**Pull request merged**
