### PR TITLE
sudo write does not work in neovim

### PR DESCRIPTION
**Pull request by zhujinxuan**
# Problem
sudo tee % cannot work in neovim. see https://github.com/neovim/neovim/issues/1716

# Fix
By adding suda.vim https://github.com/lambdalisue/suda.vim

### CODE REVIEW

**Comment by wsdjeg** [comment]
sorry. I do not want to add plugins to core layer now. my current work is to create a mini version of spacevim. for such a simple function. We can implement without plugins. and I do not like the idea of add `suda:` to the path. it is not same as `ssh:` `file:` `http:`. which can be accept by other app.

**Comment by zhujinxuan** [comment]
Cool.  I will isolate `w!! and W` in a sudo layer and get the suda logic about `w !sudo ` into that sudo layer.  Then it would prevent adding `suda://` and new plugins

**Comment by wsdjeg** [comment]
@zhujinxuan Instead of add a plugin, maybe we can just provide a command `:W`, which support `:W!` for sudo permission.

**Comment by wsdjeg** [comment]
In SpaceVim, we have a command `:W`, but it does not support `:W!`, maybe we can  improve it.

**Comment by zhujinxuan** [comment]
@wsdjeg What is you preferred interface for sudo read? map `r!!` or ?

**Comment by zhujinxuan** [comment]
update: isolate sudo logics in a single layer.  Do not import `suda://` and suda plugin and use the suda code inside sudo.vim

**Comment by wsdjeg** [comment]
@zhujinxuan I am not sure if we can do this, as suda.vim is under MIT LICENSE

**Comment by zhujinxuan** [comment]
@wsdjeg  Got it. I will rewrite all these functions.

**Comment by wsdjeg** [comment]
@zhangjiayin just some tips:

1. old version of vim has no function `execute()`, so you can use SpaceVim api

```vim
let s:CMP = SpaceVim#api#import('vim#compatible')
let result = s:CMP.execute(cmd)
```

2. you can move suda layer into core layer. as this feature is included in core layer by default.

3. if you defind command `W`. you can use `cnoremap w!! W`

4. we should avoid global func `SudoWriteCurrentFile`, you can defind func like this:

```vim
    call SpaceVim#mapping#space#def('nnoremap', ['f', 'W'], 'call call('
          \ . string(s:_function('s:SudoWriteCurrentFile')) . ', [])',
          \ 'save buffer with sudo', 1)

command! W call <SID>SudoWriteCurrentFile()
func! s:SudoWriteCurrentFile()
endf
```

**Comment by zhujinxuan** [comment]
@wsdjeg The tips are great.  Thank you a lot.

**Comment by zhujinxuan** [comment]
I will ask the author of suda.vim about whether we can re-use his code.

I have a replace in using the snippet. But vim think the `s:_function` is an undefined variable.  Using `s:_function` will cause config function abort.

I think we can add suda layer as an optional layer, and then map r!! as suda read. (Because I cannot come up wih no easy way to implement a sudo read)

**Comment by wsdjeg** [comment]
```vim
" function() wrapper
if v:version > 703 || v:version == 703 && has('patch1170')
  function! s:_function(fstr) abort
    return function(a:fstr)
  endfunction
else
  function! s:_SID() abort
    return matchstr(expand('<sfile>'), '<SNR>\zs\d\+\ze__SID$')
  endfunction
  let s:_s = '<SNR>' . s:_SID() . '_'
  function! s:_function(fstr) abort
    return function(substitute(a:fstr, 's:', s:_s, 'g'))
  endfunction
endif
```

this wrap is for old vim support.

**Comment by zhujinxuan** [comment]
@wsdjeg Sorry, I mean neovim thinks s:_function is an undefined variable.

**Comment by wsdjeg** [comment]
you need add this wrapper into sudo.vim

**Comment by zhujinxuan** [comment]
Thanks for your wrapper.  That works~

**Comment by lambdalisue** [comment]
If you don't like `suda://` prefix, use `let g:suda_startup = 0` to prevent initialization. You can use `suda#write({expr}[, {options}])` or `suda#read({expr}[, {options}])` directly without initialization.

<del>I'm OK if you copied the code while you follow the MIT license</del> but I don't think it's a good idea to copy the code while you can use suda.vim for your use-case.

**Comment by lambdalisue** [comment]
wait wait wait. No. This is GPL. I'm really afraid that.

**Comment by wsdjeg** [comment]
@lambdalisue  yeah， that is way I need to talk with you

**Comment by lambdalisue** [comment]
I think MIT license does not restrict usage of the code as long as users follow the license so I think I cannot stop you to copy my codes in GPL project but I would really want to say NO while I would not be happy for getting involved in GPL things.

I'm not a lawyer so I'm really nervous to get involved in GPL things.

**Comment by lambdalisue** [comment]
If you really need to copy the code (I'm nervous but...), please make sure you follow the MIT license **properly**. You probably need to copy the entire license into the script and you probably need to section the code to classify which code has copied.

**Comment by wsdjeg** [comment]
@lambdalisue  I have use many of  your plugins ，same as Shougo's，so  I need your supports. I will not copy the code.

**Comment by zhujinxuan** [comment]
Thanks to @wsdjeg and @lambdalisue .  I update this PR by loading suda.vim with `let g:suda_startup = 0`

Then the only problem is how to auto-reload buffer after write.  I use a checktime here, but it would need a user confirmation.

**Pull request merged**
