### PR TITLE
Add: go debug: vim-delve support

### PR DESCRIPTION
**Pull request by Adphi**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by wsdjeg** [comment]
we have debug layer, all key bindings has been added. instead of add vim-delve, we should make debug layer support delve.

**Comment by Adphi** [comment]
I agree with you. But I don't know how to do that ...

**Comment by wsdjeg** [comment]
I will update the plugin in debug layer

**Comment by Adphi** [comment]
Thank you very much !!

**Pull request closed without merging**
