### PR TITLE
change nvim floating window API functions

### PR DESCRIPTION
**Pull request by alanding1989**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?
Since neovim`s floating window API has changed, so creat this.
**The older** https://github.com/neovim/neovim/blob/dec3e027d902a59369550b9da8f6c10da61f06ef/runtime/doc/api.txt#L628
**The newer**
https://github.com/neovim/neovim/blob/dfb7f6b3492edfd60583f76ee064ac76b1b913d8/runtime/doc/api.txt#L646
[Please explain **in detail** why the changes in this PR are needed.]

### CODE REVIEW

**Comment by crisidev** [comment]
Any chance to get this merged @wsdjeg ?

**Comment by wsdjeg** [comment]
I am waiting for neovim v0.4.0.

**Comment by crisidev** [comment]
Ah ok, it makes sense to wait for the RC at least. Thanks!

**Comment by wsdjeg** [comment]
hmm why this pr is merged? @alanding1989 your defx branch is based on this PR?

**Comment by alanding1989** [comment]
> hmm why this pr is merged? @alanding1989 your defx branch is based on this PR?
Sorry, I just saw your comment now, have you merged this into SpaceVim master branch, I don`t know that I reverted the commit would influence this PR here....

**Comment by wsdjeg** [comment]
let's redo it when neovim 0.4.0 is released.

**Comment by alanding1989** [comment]
> hmm why this pr is merged? @alanding1989 your defx branch is based on this PR?
I have created a same PR, is it ok to let the PR stay open ?
Duplicate of #2710 
[https://github.com/SpaceVim/SpaceVim/pull/2762](url)

**Pull request merged**
