### PR TITLE
Update statusline after signify updated

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

The statusline should be updated after sign updated.

### CODE REVIEW

**Comment by wsdjeg** [comment]
@mhinz, Hello, I just want to update the stausline's hunk when sign finished, I have try woth `autocmd User SignifySetup * let &l:statusline = SpaceVim#layers#core#statusline#get(1)`, but It seems do not work. I use  `sy#repo#get_stats()` to get status info.

**Comment by mhinz** [comment]
As the docs say, `SignifySetup` only triggers once after `plugin/signify.vim` has been read.

What are you trying to solve in the first place? Usually, when the signs got updated and the statusline uses `sy#repo#get_stats()`, it should be updated automatically.

E.g. for quick testing: `:set stl=%!string(sy#repo#get_stats())`

**Comment by wsdjeg** [comment]
when save a file, It will update sign automatically, but after the sign has been updated no event tell me that I should update the statusline, I do not use `%{FunctionFoo()}` in statusline, so I need to update the statusline manually.

**Comment by wsdjeg** [comment]
let @+= &l:statusline, I see:

```
%#SpaceVim_statusline_a#%{SpaceVim#layers#core#statusline#mode(mode())} %{ get(w:, "winid", winnr()) } %#SpaceVim_statusline_a_SpaceVim_statusline_b#%#SpaceVim_statusline_b#%{ &modified ? ' * ' : ' - '}3.3k 2019-01-30-use-vim-as-a-javascript-ide.md %#SpaceVim_statusline_b_SpaceVim_statusline_c#%#SpaceVim_statusline_c#%{empty(&ft)? "" : " " . &ft . " "}%#SpaceVim_statusline_c_SpaceVim_statusline_b#%#SpaceVim_statusline_b# # s  %#SpaceVim_statusline_b_SpaceVim_statusline_c#%#SpaceVim_statusline_c# jside (1m0s) %#SpaceVim_statusline_c_SpaceVim_statusline_b#%#SpaceVim_statusline_b# 8+ 2~ %#SpaceVim_statusline_b_SpaceVim_statusline_c#%#SpaceVim_statusline_b_SpaceVim_statusline_z#%#SpaceVim_statusline_z#%=%#SpaceVim_statusline_b_SpaceVim_statusline_z#%#SpaceVim_statusline_b#%{" " . g:_spacevim_statusline_fileformat . " | " . (&fenc!=""?&fenc:&enc) . " "}%#SpaceVim_statusline_c_SpaceVim_statusline_b#%#SpaceVim_statusline_c# %l:%c %#SpaceVim_statusline_b_SpaceVim_statusline_c#%#SpaceVim_statusline_b# %P %#SpaceVim_statusline_c_SpaceVim_statusline_b#
```

**Comment by mhinz** [comment]
~~I see. Well, I'll introduce a new user event. I'll ping you in a few minutes. ;]~~

Wait, does using `Signify` instead of `SignifySetup` work?

**Comment by wsdjeg** [comment]
It works, Thanks.

**Pull request merged**
