### PR TITLE
Add comment space

### PR DESCRIPTION
**Pull request by jetm**
New keymap: `[SPC] c l` for comment and uncomment lines

Use nerdcommenter plugin to do the line code comments. Add nercommenter configuration.

### CODE REVIEW

**Comment by jetm** [comment]
@wsdjeg: before accepting this pull request, could you help how to read nerdcommenter settings a put in config/plugins/nerdcommenter.vim file?
I couldn't figure out how to read the settings from that file.

**Comment by wsdjeg** [comment]
@jetm  you need to change 
`\ ['scrooloose/nerdcommenter'],`
to 
`\ ['scrooloose/nerdcommenter', {'loadconf' : 1}],`
in https://github.com/SpaceVim/SpaceVim/blob/testcomment/autoload/SpaceVim/layers/edit.vim

**Comment by wsdjeg** [comment]
@jetm BTW, we should keep same mappings as spacemacs, in spacemacs `SPC c l` is for toggle comment lines.

**Comment by L-stt** [comment]
I also think `SPC c l` is better, I hate press a key twice at a time.

**Comment by jetm** [comment]
@wsdjeg & @L-stt: Thanks for the feedback. I have added `loadconf` in nerdcommenter and changed keymap to `SPC c l` .

**Comment by wsdjeg** [comment]
LGTM, merged, thanks!

**Pull request merged**
