### PR TITLE
Add format_on_save toggle for javascript

### PR DESCRIPTION
**Pull request by mekanix**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]

I used python.vim as an example how `format_on_save` is handled and added it to javascript.

### CODE REVIEW

**Comment by wsdjeg** [comment]
in javascript layer you can use following instead:

```
 let s:format_on_save = get(a:var,
        \ 'format_on_save',
        \ s:format_on_save)
```

`format-on-save` is just for backword compatible in python layer.

**Comment by mekanix** [comment]
It's amended.

**Comment by wsdjeg** [comment]
Thanks, and can you update the `lang#javascript` layer doc.

**Comment by mekanix** [comment]
Done.

**Review by wsdjeg — APPROVED** [review]

**Comment by wsdjeg** [comment]
Merged, thanks.

**Pull request merged**
