### PR TITLE
Add keymap for using Grepper in Visual mode

### PR DESCRIPTION
**Pull request by jyscao**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

It's a useful functionality from Grepper.
See: https://github.com/mhinz/vim-grepper/wiki/using-the-operator

### CODE REVIEW

**Comment by wsdjeg** [comment]
Why do not use `gs` instead?

**Comment by jyscao** [comment]
Because you already mapped `gs` in visual mode with `vnoremap gs <Plug>(openbrowser-search)` in file `config/plugins/open-browser.vim`

**Comment by jyscao** [comment]
Anything in this PR you think should be modified?

**Comment by wsdjeg** [comment]
merged

**Pull request merged**
