### PR TITLE
Add a new layer: CtrlSpace (plugin)

### PR DESCRIPTION
**Pull request by jyscao**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

This is an excellent plugin for managing workflow and project navigation.

### CODE REVIEW

**Comment by wsdjeg** [comment]
what is the status of this PR?

**Comment by jyscao** [comment]
It's good to go really, just waiting for you to merge it.

Just let me know if there's anything you'd like for me to add (comments, docs, etc.)

**Comment by jyscao** [comment]
And needless to say, I shall of course maintain this layer should you decide to merge it.

Also I remember you mentioned when we briefly discussed this plugin in Telegram previously that SpaceVim bindings could created for this plugins functionalities.

I can do that if you insist, though as I'd pointed out before, that essentially defeats the central purpose of this plugin, which is to provide a dedicated method for navigating buffers/files/tabs/projects, and strictly those.

Unlike unite, denite and fzf, it doesn't try to be a generalist by allowing one to extend functionality by supplying other sources to search through.

**Comment by jyscao** [comment]
Is there anything you want me to add/update/improve for this PR?

**Comment by wsdjeg** [comment]
@jyscao I am so sorry for late reply, I think the missing content is :

1. there should be a doc page about the layer.

2. in SpaceVim, the fuzzy finder layer contains: denite, unite, fzf, leaderf and ctrlp. both of them implement following key binding:

| Key bindings         | Discription                   |
| -------------------- | ----------------------------- |
| `<Leader> f <Space>` | Fuzzy find menu:CustomKeyMaps |
| `<Leader> f p`       | Fuzzy find menu:AddedPlugins  |
| `<Leader> f e`       | Fuzzy find register           |
| `<Leader> f h`       | Fuzzy find history/yank       |
| `<Leader> f j`       | Fuzzy find jump, change       |
| `<Leader> f o`       | Fuzzy find outline            |
| `<Leader> f q`       | Fuzzy find quick fix          |

**Comment by wsdjeg** [comment]
BTW, I do not sure if no-english user like to use this plugin, because most of us use `Ctrl-Space` to switch input methon between local and english.

**Comment by jyscao** [comment]
> BTW, I do not sure if no-english user like to use this plugin, because most of us use `Ctrl-Space` to switch input methon between local and english.

Good point. I'll make sure to add a layer local option to allow users to change the default mapping.

**Comment by jyscao** [comment]
@wsdjeg Please review the addition to the layers I've made. All the keybindings you mentioned for the other fuzzy finder layers, such as for registers, jumps, histories, etc. don't apply to this plugin, as it doesn't track anything except for buffers, files, tabs, and projects (git, mercurial, svn, etc.)

Just to point out a couple things for your convenience (all explained in the doc page btw):

1. `home-mapping-key` can be changed to anything the user likes, as to not conflict with their existing keybindings.

2. a) I added 14 SpaceVim styled keybindings which will invoke the plugin to list/search buffers/files/tabs/projects and such.
b) These bindings can be optionally enabled using a layer local setting `enable-spacevim-styled-keys`
c) They are disabled by default, because as I'd mentioned previously, I feel their use run counter to the design philosophy of this great plugin, and relying on them means using the plugin far below its full potential. But they're at least there and available to anyone who want to use them.

**Comment by wsdjeg** [comment]
when enable this layer, people can not fuzzy find installed plugins outline etc. so they need to enable another fuzzy find layer. 

so when people enable this layer and denite layer toghter, the key binding `SPC p f` will not work. this two layer use same key bindings.

**Comment by jyscao** [comment]
>so when people enable this layer and denite layer toghter, the key binding SPC p f will not work. this two layer use same key bindings.

Actually this shouldn't be a problem, because the default setting is for CtrlSpace's SpaceVim styled keybindings disabled, and just use the plugin through its main keybinding `<C-Space>`, `<C-p>` or whatever else users prefer, which I believe is the correct way of using the plugin.

See my screenshot below, where both Denite & CtrlSpace layers are enabled. With Denite's project file searching buffer pulled up through `SPC p f`, and CtrlSpace buffer list pulled up with `<C-Space>`.

Edit: for some reason my screenshot upload to GitHub keeps failing, so here's the image uploaded to Imgur: https://imgur.com/a/GX5srwL

**Comment by wsdjeg** [comment]
OK. Let' s merge it. and I will lookinto this plugin to see if we can create source for it. maybe I will fork this plugin into spacevim org.

**Comment by jyscao** [comment]
Glad to see it merged, thanks

I'll also look into seeing if it's convenient to add additional sources for
this plugin.

Since I've been meaning to fork it myself, as I plan to add an option to
disable its file caching system, which I believe is unnecessary for most
cases. I'll let you know when that's completed.

**Pull request merged**
