### PR TITLE
Add a download guard

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
To prevent the shell from executing incomplete downloads it might be useful to wrap the whole install script in a guard function instead of executing whatever part was downloaded.

### CODE REVIEW

**Comment by wsdjeg** [comment]
Thanks!

**Comment by wsdjeg** [comment]
@Leonidas-from-XIV we need change last line `guard` to `guard $@`, this will make install script support argv.

**Comment by Leonidas-from-XIV** [comment]
Great. But as a side-note, the CLA bot seems to be a bit misconfigured, it wants me to sign a CLA for SAP?

**Comment by wsdjeg** [comment]
Yeah, it just is a bot. Request for cla.

**Pull request merged**
