### PR TITLE
Add lsp support for java

### PR DESCRIPTION
**Pull request by wsdjeg**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [ ] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [ ] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

Improve lsp support for Java.

### CODE REVIEW

**Comment by ck3mp3r** [comment]
The two LSPs to test this with are:
* https://github.com/georgewfraser/java-language-server
* https://github.com/eclipse/eclipse.jdt.ls

**Comment by wsdjeg** [comment]
rename

**Comment by wsdjeg** [comment]
tagbar
fzoutline

**Comment by wsdjeg** [comment]
javadoc

**Comment by wsdjeg** [comment]
javadoc

**Pull request merged**
