### PR TITLE
Fix ycm support

### LINKED ISSUE #838: Disable CompleteParameter plugin with using ultisnips and autocompletion
Hello,
I was wondering if it is possible to disable CompleteParameter.vim when using "smart" Tab.

It does not play nice with ultisnips and YCM (which I use a lot) and it is hardcoded in the autocompletion behavior when typing "(" after a method.

Thanks

### PR DESCRIPTION
**Pull request by wsdjeg**
close #838

### CODE REVIEW

**Comment by crisidev** [comment]
Any blocker to have this PR merged?

**Comment by wsdjeg** [comment]
@crisidev I am so sorry, I do not use ycm as default completion engine, please wait.

**Comment by crisidev** [comment]
@wsdjeg, sure, no problem. Anything I can do to help?

**Comment by crisidev** [comment]
This PR broke YCM support as removing supertab as a dependency stopped tab from working as selector of completion. Also it does not fix #838.

Now tab _always_ insert a tab.

**Comment by wsdjeg** [comment]
what is the `:imap <Tab>` output in your vim?

**Comment by crisidev** [comment]
This is what I have mapped as tab right now without SuperTab installed.

```
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
```

**Comment by wsdjeg** [comment]
ok, will reopen that issue.

**Comment by crisidev** [comment]
Should I reopen the issue?

**Comment by wsdjeg** [comment]
yeah， of cause

**Pull request merged**
